"""update_connection_index_for_fb_pages

Revision ID: 067ac10f57fb
Revises: a1b2c3d4e5f6
Create Date: 2026-02-25 01:53:34.703217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '067ac10f57fb'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_connections_user_provider_active', table_name='connections', postgresql_where='(revoked_at IS NULL)')
    op.create_index('ix_connections_user_provider_active_v2', 'connections', ['user_id', 'provider', sa.literal_column("COALESCE(provider_user_id, '')")], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_connections_user_provider_active_v2', table_name='connections', postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('ix_connections_user_provider_active', 'connections', ['user_id', 'provider'], unique=True, postgresql_where='(revoked_at IS NULL)')
    op.alter_column('connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
