"""Add YouTube tokens table

Revision ID: 46555185322c
Revises: fb4e0e1c0e69
Create Date: 2025-10-20 01:40:14.816032

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "46555185322c"
down_revision: Union[str, None] = "fb4e0e1c0e69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
