"""empty message

Revision ID: ebd5dc3e1748
Revises: 1bb804ba4ace
Create Date: 2025-11-04 19:41:10.261357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ebd5dc3e1748"
down_revision: Union[str, None] = "1bb804ba4ace"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_id", table_name="transactions")
    op.drop_index("ix_transactions_stripe_payment_intent_id", table_name="transactions")
    op.drop_index("ix_transactions_subscription_id", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("ix_subscriptions_id", table_name="subscriptions")
    op.drop_index("ix_subscriptions_stripe_customer_id", table_name="subscriptions")
    op.drop_index("ix_subscriptions_stripe_subscription_id", table_name="subscriptions")
    op.drop_index("ix_subscriptions_user_id", table_name="subscriptions")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "stripe_customer_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "stripe_subscription_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("stripe_price_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "stripe_product_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("plan", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "trial_start", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "trial_end", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "current_period_start",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "current_period_end",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "cancel_at_period_end", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "canceled_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="subscriptions_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="subscriptions_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "ix_subscriptions_user_id", "subscriptions", ["user_id"], unique=False
    )
    op.create_index(
        "ix_subscriptions_stripe_subscription_id",
        "subscriptions",
        ["stripe_subscription_id"],
        unique=True,
    )
    op.create_index(
        "ix_subscriptions_stripe_customer_id",
        "subscriptions",
        ["stripe_customer_id"],
        unique=True,
    )
    op.create_index("ix_subscriptions_id", "subscriptions", ["id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("subscription_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "stripe_payment_intent_id",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "stripe_invoice_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("currency", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "transaction_type", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("receipt_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name="transactions_subscription_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="transactions_pkey"),
    )
    op.create_index(
        "ix_transactions_subscription_id",
        "transactions",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_stripe_payment_intent_id",
        "transactions",
        ["stripe_payment_intent_id"],
        unique=True,
    )
    op.create_index("ix_transactions_id", "transactions", ["id"], unique=False)
    # ### end Alembic commands ###
